{% set name = "torchtnt" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchtnt-{{ version }}.tar.gz
    sha256: 06e8184f58d15307bf342fcf2ed11a3dd8d00f3d715b08f3792af2f48a2d5970
  - url: https://raw.githubusercontent.com/pytorch/tnt/master/requirements.txt
    sha256: 7a91d0f97c358e1b0735d6c8a77d947cd792e6e0f8df96aee0c5ec6bc894cdd6
  - url: https://raw.githubusercontent.com/pytorch/tnt/master/dev-requirements.txt
    sha256: 9cfc5c36242e99db8d7c59c05dfcf970e6b8daeaac16467b1c11baa15831534e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - fsspec
    - numpy
    - packaging
    - psutil
    - pyre-extensions
    - python >=3.7
    - setuptools
    - tensorboard
    - pytorch
    - tabulate
    - torchsnapshot
    - tqdm
    - typing-extensions

test:
  imports:
    - torchtnt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytorch/tnt
  summary: A lightweight library for PyTorch training tools and utilities
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
