{% set name = "torchtnt" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torchtnt-{{ version }}.tar.gz
    sha256: 26cf4e718965afc293e76158b47283722055bcf79e94d0e67e70b5dbf61c0c9b
  - url: https://raw.githubusercontent.com/pytorch/tnt/master/requirements.txt
    sha256: 3014de0cda5b7f3a17ee67da00d78cedf617d0cab2e49d636923dbe9ca36547f
  - url: https://raw.githubusercontent.com/pytorch/tnt/master/dev-requirements.txt
    sha256: e0163f410464bdf95d4e2bcbebe4dee1bc62151c5ab8aa58ee1de8cd3e1eee89

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - fsspec
    - numpy
    - packaging
    - psutil
    - pyre-extensions
    - python >={{ python_min }}
    - setuptools
    - tensorboard
    - pytorch
    - tabulate
    - torchsnapshot
    - tqdm
    - typing-extensions

test:
  imports:
    - torchtnt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pytorch/tnt
  summary: A lightweight library for PyTorch training tools and utilities
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
