{% set name = "torchtnt" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchtnt-{{ version }}.tar.gz
    sha256: 26cf4e718965afc293e76158b47283722055bcf79e94d0e67e70b5dbf61c0c9b
  - url: https://raw.githubusercontent.com/pytorch/tnt/master/requirements.txt
    sha256: 7a91d0f97c358e1b0735d6c8a77d947cd792e6e0f8df96aee0c5ec6bc894cdd6
  - url: https://raw.githubusercontent.com/pytorch/tnt/master/dev-requirements.txt
    sha256: def1d652ba72dc51fa52467bd35880b53ea39f597f5513e9819aa5bf8db0c76c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - fsspec
    - numpy
    - packaging
    - psutil
    - pyre-extensions
    - python >=3.7
    - setuptools
    - tensorboard
    - pytorch
    - tabulate
    - torchsnapshot
    - tqdm
    - typing-extensions

test:
  imports:
    - torchtnt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytorch/tnt
  summary: A lightweight library for PyTorch training tools and utilities
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
